# Generated by Django 4.2.3 on 2023-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_rename_advertisements_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='Отметьте, если торг уместен', verbose_name='торг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
